### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#18]

**Comment by samverdad** [comment]
_Database name:_ **quizbee**

_Tables..._

**admin**
- admin_id [int(10)] _primary key_
- admin_username [varchar(255)] _unique key_
- admin_pw [varchar(255)]

**quiz**
- quiz_id [int(10)] _primary key_
- quiz_name [varchar(255)]
- quiz_code [varchar(10)] _unique key_
- quiz_creation [timestamp]
- quiz_start [timestamp]
- quiz_end [timestamp]
- host_id [int(10)]

**host**
- host_id [int(10)] _primary key_
- host_email [varchar(255)] _unique key_
- host_username [varchar(255)] _unique key_
- host_pw [varchar(255)]
- host_school [varchar(255)]
- host_towncity [varchar(255)]
- host_provincestate [varchar(255)]
- host_regdate [timestamp]

**contestant**
- contestant_id [int(10)] _primary key_
- contestant_username [varchar(255)] _unique key_
- contestant_pw [varchar(255)]
- contestant_regdate [timestamp]
- host_id [int(10)]

**participant**
- participant_id [int(10)] _primary key_
- participant_name [varchar(255)]
- contestant_id [int(10)]

**difficulty**
- difficulty_id [int(10)] _primary key_
- difficulty_name [varchar(255)]
- difficulty_points [int(10)]
- difficulty_min [int(10)]
- difficulty_sec [int(10)]

**qtype**
- qtype_id [int(10)] _primary key_
- qtype_option [varchar(255)]

**question**
- question_id [int(10)] _primary key_
- question_entry [text]
- question_state [int(2)]
- qtype_id [int(10)]
- difficulty_id [int(10)]
- host_id [int(10)]

**answer**
- answer_id [int(10)] _primary key_
- answer_entry [text]
- question_id [int(10)]

**option**
- option_id [int(10)] _primary key_
- option_entry [varchar(255)]
- answer_id [int(10)]

**score**
- score_id [int(10)] _primary key_
- score_points [int(10)]
- difficulty_id [int(10)]
- contestant_id [int(10)]

**Comment by samverdad** [comment]
@EarlChan This is your guide to create database, tables, and fields in PHPMyAdmin.

**Comment by samverdad** [comment]
@EarlChan This is your guide to create database, tables, and fields in PHPMyAdmin.

**Comment by EarlChan** [comment]
sarah reserve word yung "option" kaya "options" ang ginawa ko
