### ISSUE TITLE
Coded contestant's dashboard design without content and unfunctional

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#29]

**Comment by blesanne** [comment]
1. What is the Countdown Timer?
The countdown timer is a feature that actually sets a time limit on a survey. Respondents have to complete the survey within a certain period of time. When the timer runs out, the survey closes and the responses are marked as incomplete. The minimum time limit is 1 minute and the maximum is 60 minutes.

How do I set up a time limit for my survey?

To set up time limit for the survey, go to:

Login »  Surveys »  (Select Survey) »  Edit Survey » Settings »  Security
Use the drop-down to select the number of minutes for the timer, with a minimum time of 1 minute and a maximum time of 60 minutes.
Click Save.
How does the time limit work?

A countdown timer will be displayed on the survey. Respondents have to finish the survey within the specified time. If respondents do not finish the survey within the specified time, the survey will end and the response will be marked as incomplete.

2.https://www.qualtrics.com/support/survey-platform/survey-module/editing-questions/question-types-guide/advanced/timing/
