### ISSUE TITLE
Identify user requirements for the website

### ISSUE THREAD

**Issue by louiealmeda** [IT3A-2016/Cypher#3]

**Comment by junitzkie** [comment]
Host/Contestant requirements:

1.) Register (for host only)
-the user/host must register the contestants first for them to join the quiz.

2.) Log-in (for host/contestant)
-the user must be able to log-in to start the quiz.
-the account will be logged in by either host or  the contestant.

3.) User-Friendly User Interface (for host and Contestant)
- pleasant UI helps the user/contestant to think and answer the questions properly.
- pleasant/presentable  UI for the host.

4.) Update or insert Questions (for host only)
- the host must be able to insert questions for the quiz, or update questions if something is wrong.

5.)Scores viewing and Tally (for host only)
- the host of the quiz bee should be able to view and tally the scores of the contestants to know the winner.

6.)

**Comment by junitzkie** [comment]
Host/Contestant requirements:

1.) Register (for host only)
- the user/host must register the contestants first for them to join the quiz.

2.) Log-in (for host/contestant)
- the user must be able to log-in to start the quiz.
- the account will be logged in by either host or  the contestant.

3.) User-Friendly User Interface (for host and Contestant)
- pleasant UI helps the user/contestant to think and answer the questions properly.
- pleasant/presentable  UI for the host.

4.) Update or insert Questions (for host only)
- the host must be able to insert questions for the quiz, or update questions if something is wrong.

5.)Scores viewing and Tally (for host only)
- the host of the quiz bee should be able to view and tally the scores of the contestants to know the winner.
