### ISSUE TITLE
Research and study how to upload and display pictures using PHP

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#36]

**Comment by junitzkie** [comment]
uploading pictures using php

http://www.htmlgoodies.com/beyond/php/article.php/3877766/Web-Developer-How-To-Upload-Images-Using-PHP.htm
https://davidwalsh.name/basic-file-uploading-php

diplaying pictures using php
http://stackoverflow.com/questions/23842268/how-to-display-image-from-database-using-php
http://stackoverflow.com/questions/19563639/displaying-an-image-using-a-php-variable

upload&display
https://vikasmahajan.wordpress.com/2010/07/07/inserting-and-displaying-images-in-mysql-using-php/
https://www.quora.com/How-can-we-display-an-uploaded-image-on-a-page-in-PHP-before-it-is-stored-to-the-database

upload and display video
https://www.youtube.com/watch?v=jYZDJ-twqh8
