### ISSUE TITLE
Identify the main possible features for the website

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#4]

**Comment by blesanne** [comment]
Features of website 
1.Your data private to your account.
      You must log-in whether you are a host or a contestant and so that your data will be protected in our website.
2.View graded results & selected answers.
       It can be instantly be produced in different ways.
3.Completely Web Based
      You can do everything in your web browser. Make a quiz, distribute your quiz, and view reports completely online.
4.Detailed Reports
      This Quiz Bee needed the  most powerful feature is its reports in every contestant.
