### ISSUE TITLE
Identify the specific features for contestant's dashboard

### ISSUE THREAD

**Issue by samverdad** [IT3A-2016/Cypher#6]

**Comment by blesanne** [comment]
You should have known the Title of the Quiz bee.
You should have Information about contestant 
You should have Timer just to known whether they need to answer fastly.
You should have Questioned to be asked and distribute it properly.
You should include interactive elements into your school quiz bee, such as buttons that trigger audio prompts or a running total of the player’s score on the bottom of the screen. 
You may also allow the participants to enter in text into the quiz to answer a question or have a results screen at the end of the quiz.
You may also include interesting background images in the school quiz bee and make the quiz appear visually appealing so the participants are more engaged in the content.
